version: '3.4'

x-defaults: &defaults
  restart: always
  build: .
  depends_on:
    - redis
  env_file: .env
  environment:
    INTRAMURAL_REDIS_HOST: redis

services:
  redis:
    restart: always
    image: redis:3.2-alpine

  web:
    <<: *defaults
    ports:
      - '9005:9005'
    command: run:web
  worker:
    <<: *defaults
    command: run:worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  intramural-postgres:
    external: true